language: python

python:
  - "3.5"
  - "3.4"
  - "2.7"

sudo: required

services:
  - docker

install:
  - pip install -r requirements.txt

before_script:
  - docker run -d -p 127.0.0.1:1883:1883 thethingsnetwork/rabbitmq

script:
  - pep8 --first ttnmqtt/ttnmqtt.py
  - pep8 --first test_ttnmqtt.py
  - pytest --cov=ttnmqtt --cov-report html test_*.py
